version: "3.9"

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    env_file:
      - .env
    networks:
      - dblab-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dblab-net"
      - "traefik.http.routers.openwebui.rule=Host(`demo-dblab.tsechoev.dev`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls.certresolver=cloudflare"
      - "traefik.http.services.openwebui.loadbalancer.server.port=8080"

networks:
  dblab-net:
    external: true
