name: Cleanup DBLab Branch Env

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-dblab-env:
    runs-on: ubuntu-latest

    steps:
      - name: Delete DBLab clone
        run: |
          CLONE_ID="pr_${{ github.event.pull_request.number }}_clone"

          echo "Deleting DBLab clone: $CLONE_ID"

          curl -s -X DELETE \
            -H "Verification-Token: ${{ secrets.DBLAB_TOKEN }}" \
            ${{ secrets.DBLAB_API_URL }}/clone/${CLONE_ID} || echo "Clone delete request failed or not found, ignoring."

      - name: Delete DBLab branch
        run: |
          BRANCH_ID="pr-${{ github.event.pull_request.number }}"

          echo "Deleting DBLab branch: $BRANCH_ID"

          curl -s -X DELETE \
            -H "Verification-Token: ${{ secrets.DBLAB_TOKEN }}" \
            ${{ secrets.DBLAB_API_URL }}/branch/${BRANCH_ID} || echo "Branch delete request failed or not found, ignoring."

      - name: Stop & remove OpenWebUI container
        run: |
          CONTAINER_NAME="openwebui-pr-${{ github.event.pull_request.number }}"

          if docker ps -a --format '{{.Names}}' | grep -q "$CONTAINER_NAME"; then
            echo "Stopping container: $CONTAINER_NAME"
            docker stop $CONTAINER_NAME || true
            echo "Removing container: $CONTAINER_NAME"
            docker rm $CONTAINER_NAME || true
          else
            echo "No container named $CONTAINER_NAME found, skipping."
          fi
