name: Cleanup DBLab Branch Env

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for ${{ github.event }})
        uses: actions/checkout@v4

      - name: SSH cleanup on remote host
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e
            PR_NUM=${{ github.event.pull_request.number }}
            CLONE_ID="pr_${PR_NUM}_clone"
            APP_CONTAINER="openwebui_pr_${PR_NUM}"

            echo "🛑 Stopping and removing OpenWebUI container $APP_CONTAINER"
            docker rm -f $APP_CONTAINER || true

            echo "🛑 Disconnecting clone from dblab-net"
            docker network disconnect dblab-net $CLONE_ID || true

            echo "🛑 Removing DBLab clone container $CLONE_ID"
            docker rm -f $CLONE_ID || true

      - name: Delete DBLab clone via API
        env:
          DTLAB_TOKEN: ${{ secrets.DBLAB_TOKEN }}
          API_URL: ${{ secrets.DBLAB_API_URL }}
        run: |
          CLONE_ID="pr_${{ github.event.pull_request.number }}_clone"
          echo "🔐 Deleting DBLab clone $CLONE_ID"
          curl -s -X DELETE \
            -H "Verification-Token: $DTLAB_TOKEN" \
            "$API_URL/clone/$CLONE_ID" \
          && echo "Deleted clone $CLONE_ID" || true

      - name: Delete DBLab branch via API
        env:
          DTLAB_TOKEN: ${{ secrets.DBLAB_TOKEN }}
          API_URL: ${{ secrets.DBLAB_API_URL }}
        run: |
          BRANCH="pr-${{ github.event.pull_request.number }}"
          echo "🔐 Deleting DBLab branch $BRANCH"
          curl -s -X DELETE \
            -H "Verification-Token: $DTLAB_TOKEN" \
            "$API_URL/branch/$BRANCH" \
          && echo "Deleted branch $BRANCH" || true
